DELETE http://localhost:3003/api/blogs/67476a5769c15644c7922d61
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzQ3NWVlYjY5YzM5MWY2MTE1Mzc5NjMiLCJpYXQiOjE3MzI3MzMxNzcsImV4cCI6MTczMjczNjc3N30.5B11XJo7QGUDCkCmbZ1YKjoRWklTebM-1-gMTBrCI8w
