POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Test Author3", 
    "title": "This is a test title3",
    "url": "https://fullstackopen.com/en/part3/",
    "likes": 500
}
