POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Test Author2", 
    "title": "This is a test title2",
    "url": "https://fullstackopen.com/en/part4/",
    "likes": 499
}
