POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Test Author", 
    "title": "This is a test title",
    "url": "https://fullstackopen.com/en/",
    "likes": 500
}
